CREATE TABLE schedule (
    id INT NOT NULL AUTO_INCREMENT,
    todo VARCHAR(100) NULL COMMENT '스케쥴',
    author VARCHAR(100) NOT NULL COMMENT '작성자',
    password VARCHAR(50) NOT NULL COMMENT '비밀번호',
    date DATETIME NULL,
    CONSTRAINT CALENDAR_PK PRIMARY KEY(id)
);